<?php
namespace StringSwap;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

require_once __DIR__."/../../lib/Thrift/Exception/TApplicationException.php";
require_once __DIR__."/../../lib/Thrift/Base/TBase.php";
require_once __DIR__."/../../lib/Thrift/Type/TMessageType.php";

require_once __DIR__."/Types.php";
interface StringSwapIf {
  /**
   * @param string $textToSwap
   * @return string
   */
  public function swap($textToSwap);
  /**
   */
  public function ping();
}


class StringSwapClient implements \StringSwap\StringSwapIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function swap($textToSwap)
  {
    $this->send_swap($textToSwap);
    return $this->recv_swap();
  }

  public function send_swap($textToSwap)
  {
    $args = new \StringSwap\StringSwap_swap_args();
    $args->textToSwap = $textToSwap;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'swap', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('swap', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_swap()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\StringSwap\StringSwap_swap_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \StringSwap\StringSwap_swap_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("swap failed: unknown result");
  }

  public function ping()
  {
    $this->send_ping();
    $this->recv_ping();
  }

  public function send_ping()
  {
    $args = new \StringSwap\StringSwap_ping_args();
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ping', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ping', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ping()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\StringSwap\StringSwap_ping_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \StringSwap\StringSwap_ping_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    return;
  }

}


// HELPER FUNCTIONS AND STRUCTURES

class StringSwap_swap_args extends TBase {
  static $_TSPEC;

  /**
   * @var string
   */
  public $textToSwap = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'textToSwap',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'StringSwap_swap_args';
  }

  public function read($input)
  {
    return $this->_read('StringSwap_swap_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('StringSwap_swap_args', self::$_TSPEC, $output);
  }

}

class StringSwap_swap_result extends TBase {
  static $_TSPEC;

  /**
   * @var string
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'StringSwap_swap_result';
  }

  public function read($input)
  {
    return $this->_read('StringSwap_swap_result', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('StringSwap_swap_result', self::$_TSPEC, $output);
  }

}

class StringSwap_ping_args extends TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'StringSwap_ping_args';
  }

  public function read($input)
  {
    return $this->_read('StringSwap_ping_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('StringSwap_ping_args', self::$_TSPEC, $output);
  }

}

class StringSwap_ping_result extends TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'StringSwap_ping_result';
  }

  public function read($input)
  {
    return $this->_read('StringSwap_ping_result', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('StringSwap_ping_result', self::$_TSPEC, $output);
  }

}


